environment             = "prd"
lambda_function_earaujo = "prd-us-east-1-beca-2026-lambda-pokeapi"
s3_bucket_earaujoo      = "prd-us-east-1-beca-2026-bucket-pokeapi"
glue_job_lz_to_sor      = "prd-us-east-1-beca-2026-glue-job-lz-bronze-pokeapi"
glue_job_sor_to_sot     = "prd-us-east-1-beca-2026-glue-job-bronze-silver-pokeapi"
glue_job_sot_to_spec    = "prd-us-east-1-beca-2026-glue-job-silver-gold-pokeapi"
step_function_tform     = "prd-us-east-1-beca-2026-step-function-pokeapi"
