name: "Develop Workflow"

on:
  push:
    branches:
      - desenvolvedor

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/00-terraform.yml

    with:
      environment: "dev"

      # SUA ROLE (substituir pelo seu ARN real)
      aws-assume-role-arn: "arn:aws:iam::606120284293:role/github-actions-terraform-earaujoo"

      aws-region: "us-east-1"

      # SEUS recursos
      aws-statefile-s3-bucket: "bucket-earaujo-dev"

      aws-lock-dynamodb-table:  "earaujo-terraform-lock"